### ISSUE TITLE
Add a small config file easyfront.json

### ISSUE THREAD

**Issue by madroneropaulo** [lavrton/easyfront#6]
I know, the idea is to make it easy with no configs, but sometimes you really need some configs like port for dev server or specific modules version. So a config file easyfront.json should be added in order to administrate such small things.

In order to keep it easy, this easyfront.json should not affect at all the current process, so it can be used only in very specific cases.

At least for now a command option along with the init command should be available in order to start the server at a different port as 8080 is commonly used by many other applications.

**Comment by carl0zen** [comment]
+1 for this, I really need to expand the current stack, I think this is a great start, but sometimes I need the flexibility to customize my setup, that would avoid the need of having to fork the repo. Thank you very much for this, has made my life so much easier

**Comment by lavrton** [comment]
Right. I will take a look very soon.

**Comment by carl0zen** [comment]
thank you very much @lavrton

**Comment by lavrton** [comment]
As for now I still want to avoid file configuration. I see that some options are still required. Probably it will be better to pass them into `easyfront` via command line options than via `.json` file.

**Comment by lavrton** [comment]
I added `port` option for `dev` command. https://github.com/lavrton/easyfront#local-server-port
I will close issue for now. Open another if you need some more configurations.
