### ISSUE TITLE
how do I import normalize.css from node modules into my styles file?

### ISSUE THREAD

**Issue by ericjim** [lavrton/easyfront#7]
After performing `npm install normalize.css --save`, I would like to import this library into `styles.css` as follows: `@import 'normalize.css/normalize';`.

However, I get the following error:

```
ERROR in ./~/css-loader!./src/styles.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./normalize.css/normalize in /Users/ericjimenez/Workspace/react-playground/src
 @ ./~/css-loader!./src/styles.css 3:10-86
```

In the spirit of easyfront, I would like to do zero configuration for this to work. What should I do?

Aside: thanks for easyfront, it's great!

**Comment by lavrton** [comment]
@ericjim try to set real path. eg `@import '../node_modules/normalize.css/normalize';`

**Comment by ericjim** [comment]
@lavrton Thanks that worked! Here is the exact incantation `@import '../node_modules/normalize.css/normalize.css';`
